const ASSETS={KOSPI:'^KS11',KOSDAQ:'^KQ11','S&P 500':'^GSPC',NASDAQ:'^IXIC','USD/KRW':'KRW=X',WTI:'CL=F',VIX:'^VIX'};
const U=[
['삼성전자','005930.KS','KR','반도체·AI'],['SK하이닉스','000660.KS','KR','HBM·AI 메모리'],['한미반도체','042700.KS','KR','HBM 장비'],['현대차','005380.KS','KR','자동차'],['기아','000270.KS','KR','자동차'],['두산에너빌리티','034020.KS','KR','원전·전력'],['HD현대일렉트릭','267260.KS','KR','전력 인프라'],['NAVER','035420.KS','KR','인터넷·AI'],['카카오','035720.KS','KR','플랫폼'],['삼성바이오로직스','207940.KS','KR','바이오'],['LG에너지솔루션','373220.KS','KR','배터리'],['셀트리온','068270.KS','KR','바이오'],
['NVIDIA','NVDA','US','AI GPU'],['Apple','AAPL','US','소비자 기술'],['Microsoft','MSFT','US','클라우드·AI'],['Amazon','AMZN','US','클라우드·소비'],['Alphabet','GOOGL','US','검색·클라우드·AI'],['Meta Platforms','META','US','광고·AI'],['Broadcom','AVGO','US','AI 반도체'],['AMD','AMD','US','AI 반도체'],['TSMC','TSM','US','파운드리·AI'],['Tesla','TSLA','US','전기차·로봇'],['Palantir','PLTR','US','AI 소프트웨어'],['JPMorgan','JPM','US','금융']
];
const clean=s=>(s||'').replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/<[^>]+>/g,'').trim();
const escRe=s=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
async function yahoo(t,range='3mo'){const r=await fetch('https://query1.finance.yahoo.com/v8/finance/chart/'+encodeURIComponent(t)+'?range='+range+'&interval=1d&events=div%2Csplits',{headers:{'User-Agent':'Mozilla/5.0'}});if(!r.ok)throw Error('Yahoo '+t);const j=await r.json(),res=j.chart?.result?.[0],m=res?.meta||{};if(!res)throw Error('No quote');const price=m.regularMarketPrice,prev=m.chartPreviousClose||m.previousClose,ts=res.timestamp||[],cl=res.indicators?.quote?.[0]?.close||[],vol=res.indicators?.quote?.[0]?.volume||[],history=ts.map((x,i)=>({date:new Date(x*1000).toLocaleDateString('ko-KR',{month:'numeric',day:'numeric'}),close:cl[i],volume:vol[i]})).filter(x=>Number.isFinite(x.close)),v=history.slice(-20).map(x=>x.volume).filter(Number.isFinite);return{price,change:prev?((price-prev)/prev*100):0,history,volume:v.at(-1)||0,avgVolume:v.length?v.reduce((a,b)=>a+b,0)/v.length:0,asOf:m.regularMarketTime?new Date(m.regularMarketTime*1000).toISOString():null,currency:m.currency||''}}
async function newsFor(q,lang='ko'){const us=lang==='en',r=await fetch('https://news.google.com/rss/search?q='+encodeURIComponent(q+' when:2d')+'&hl='+(us?'en-US':'ko')+'&gl='+(us?'US':'KR')+'&ceid='+(us?'US:en':'KR:ko'),{headers:{'User-Agent':'Mozilla/5.0'}});if(!r.ok)throw Error('News');const x=await r.text(),blocks=[...x.matchAll(/<item>([\s\S]*?)<\/item>/g)].map(z=>z[1]).slice(0,35),get=(b,n)=>clean((b.match(new RegExp('<'+n+'[^>]*>([\s\S]*?)<\/'+n+'>','i'))||[])[1]);return blocks.map(b=>{const title=get(b,'title'),link=get(b,'link'),pub=get(b,'pubDate'),source=get(b,'source')||'Google News',desc=get(b,'description'),image=(desc.match(/<img[^>]+src=["']([^"']+)/i)||[])[1]||'';let category='MARKET';if(/AI|반도체|HBM|GPU|데이터센터|NVIDIA|AMD|chip|semiconductor/i.test(title))category='TECH';else if(/금리|환율|연준|Fed|물가|국채|채권|rate|inflation|yield/i.test(title))category='MACRO';else if(/유가|원유|에너지|oil|energy/i.test(title))category='ENERGY';return{title,link,pubDate:pub,source,image,category,lang,timeText:pub?new Date(pub).toLocaleString('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}):''}}).filter(x=>x.title&&x.link)}
function sentiment(items){let bull=0,bear=0,neu=0;const pos=/상승|호재|급등|성장|증가|수요|기대|개선|수혜|강세|최대|record|beat|surge|growth|bullish|upgrade|buy|outperform/i,neg=/하락|악재|급락|우려|감소|둔화|경쟁|위험|약세|실망|miss|drop|fall|bearish|downgrade|sell|underperform/i;for(const n of items){if(pos.test(n.title)&&!neg.test(n.title))bull++;else if(neg.test(n.title)&&!pos.test(n.title))bear++;else neu++}const total=Math.max(1,bull+bear+neu);return{bullish:Math.round(bull/total*100),neutral:Math.round(neu/total*100),bearish:Math.round(bear/total*100),sample:bull+bear+neu}}
function calc(q,s,market){const news=Math.max(0,Math.min(100,50+(s.bullish-s.bearish)*.55)),price=Math.max(0,Math.min(100,50+q.change*7)),vol=q.avgVolume?Math.max(0,Math.min(100,50+((q.volume/q.avgVolume)-1)*30)):50,mkt=Math.max(0,Math.min(100,50+market*10)),stability=q.change<-6?30:q.change>9?45:72,score=Math.round(news*.30+price*.25+vol*.15+mkt*.15+stability*.15);return{score,components:{'뉴스 모멘텀':news,'가격 모멘텀':price,'거래량':vol,'시장 모멘텀':mkt,'변동성/안정성':stability}}}
async function one(s,market,all){let q={price:null,change:0,history:[],volume:0,avgVolume:0};try{q=await yahoo(s[1])}catch{}let rel=all.filter(n=>new RegExp(escRe(s[0]),'i').test(n.title));const se=sentiment(rel.length?rel:all),c=calc(q,se,market),reason=se.bullish>se.bearish?'뉴스 흐름 우호':se.bearish>se.bullish?'뉴스 흐름 부담':'뉴스 흐름 혼조';return{name:s[0],ticker:s[1],market:s[2],sector:s[3],score:c.score,components:c.components,signal:c.score>=85?'강한 관심':c.score>=75?'관심':c.score>=65?'관찰':'주의',reason:reason+(q.change>=0?' · 가격 강세':' · 가격 약세'),newsCount:se.sample}}
async function markets(){const o={};await Promise.all(Object.entries(ASSETS).map(async([n,t])=>{try{const q=await yahoo(t,'5d');o[n]={price:q.price,change:q.change,asOf:q.asOf,currency:q.currency};}catch(e){o[n]={price:null,change:0,asOf:null,currency:''};}}));return o}
export default async function handler(req,res){try{const mk=await markets(),m=mk['S&P 500']?.change||0;const [kr,en]=await Promise.all([newsFor('한국 주식 증시 반도체 AI 금리 환율','ko'),newsFor('US stocks market AI semiconductor Fed rates','en')]);const all=[...kr,...en].sort((a,b)=>new Date(b.pubDate)-new Date(a.pubDate));const seen=new Set(),base=all.filter(n=>{const k=n.title.toLowerCase();if(seen.has(k))return false;seen.add(k);return true});const out=(await Promise.all(U.map(s=>one(s,m,base)))).sort((a,b)=>b.score-a.score);const fresh=base.filter(n=>Date.now()-new Date(n.pubDate).getTime()<48*3600*1000).slice(0,16);res.setHeader('Cache-Control','s-maxage=60, stale-while-revalidate=300');res.status(200).json({updatedAt:new Date().toISOString(),markets:mk,picks:out.slice(0,12),news:fresh,meta:{universe:U.length,newsCount:base.length,refreshMinutes:5}})}catch(e){res.status(500).json({error:String(e),updatedAt:new Date().toISOString(),markets:{},picks:[],news:[]})}}
