const ASSETS={KOSPI:'^KS11',KOSDAQ:'^KQ11','S&P 500':'^GSPC',NASDAQ:'^IXIC','USD/KRW':'KRW=X',WTI:'CL=F',VIX:'^VIX'};
const U=[['삼성전자','005930.KS','KR','반도체·AI'],['SK하이닉스','000660.KS','KR','HBM·AI 메모리'],['한미반도체','042700.KS','KR','HBM 장비'],['현대차','005380.KS','KR','자동차'],['두산에너빌리티','034020.KS','KR','원전·전력'],['NAVER','035420.KS','KR','인터넷·AI'],['삼성바이오로직스','207940.KS','KR','바이오'],['LG에너지솔루션','373220.KS','KR','배터리'],['NVIDIA','NVDA','US','AI GPU'],['Apple','AAPL','US','소비자 기술'],['Microsoft','MSFT','US','클라우드·AI'],['Amazon','AMZN','US','클라우드·소비'],['Alphabet','GOOGL','US','검색·클라우드·AI'],['Meta Platforms','META','US','광고·AI'],['Broadcom','AVGO','US','AI 반도체'],['AMD','AMD','US','AI 반도체']];
const clean=s=>(s||'').replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/<[^>]+>/g,'').trim();
const escRe=s=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
async function yahoo(t,range='1mo'){const r=await fetch('https://query1.finance.yahoo.com/v8/finance/chart/'+encodeURIComponent(t)+'?range='+range+'&interval=1d&events=div%2Csplits',{headers:{'User-Agent':'Mozilla/5.0'}});if(!r.ok)throw Error('Yahoo '+t);const j=await r.json(),res=j.chart?.result?.[0],m=res?.meta||{};if(!res)throw Error('No quote');const price=m.regularMarketPrice,prev=m.chartPreviousClose||m.previousClose,ts=res.timestamp||[],cl=res.indicators?.quote?.[0]?.close||[],vol=res.indicators?.quote?.[0]?.volume||[],history=ts.map((x,i)=>({date:new Date(x*1000).toLocaleDateString('ko-KR',{month:'numeric',day:'numeric'}),close:cl[i],volume:vol[i]})).filter(x=>Number.isFinite(x.close)),v=history.slice(-10).map(x=>x.volume).filter(Number.isFinite);return{price,change:prev?((price-prev)/prev*100):0,history,volume:v.at(-1)||0,avgVolume:v.length?v.reduce((a,b)=>a+b,0)/v.length:0}}
async function newsFor(q){const r=await fetch('https://news.google.com/rss/search?q='+encodeURIComponent(q+' when:2d')+'&hl=ko&gl=KR&ceid=KR:ko',{headers:{'User-Agent':'Mozilla/5.0'}});if(!r.ok)throw Error('News');const x=await r.text(),blocks=[...x.matchAll(/<item>([\s\S]*?)<\/item>/g)].map(z=>z[1]).slice(0,30),get=(b,n)=>clean((b.match(new RegExp('<'+n+'[^>]*>([\\s\\S]*?)<\\/'+n+'>','i'))||[])[1]);return blocks.map(b=>{const title=get(b,'title'),link=get(b,'link'),pub=get(b,'pubDate'),source=get(b,'source')||'Google News',desc=get(b,'description'),image=(desc.match(/<img[^>]+src=["']([^"']+)/i)||[])[1]||'';let category='MARKET';if(/AI|반도체|HBM|GPU|데이터센터|NVIDIA|AMD|chip/i.test(title))category='TECH';else if(/금리|환율|연준|Fed|물가|국채|채권/i.test(title))category='MACRO';else if(/유가|원유|에너지|oil/i.test(title))category='ENERGY';return{title,link,pubDate:pub,source,image,category,timeText:pub?new Date(pub).toLocaleString('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}):''}}).filter(x=>x.title&&x.link)}
function sentiment(items){let bull=0,bear=0,neu=0;const pos=/상승|호재|급등|성장|증가|수요|기대|개선|수혜|강세|최대|record|beat|surge|growth|bullish|upgrade|buy/i,neg=/하락|악재|급락|우려|감소|둔화|경쟁|위험|약세|실망|miss|drop|fall|bearish|downgrade|sell/i;for(const n of items){if(pos.test(n.title)&&!neg.test(n.title))bull++;else if(neg.test(n.title)&&!pos.test(n.title))bear++;else neu++}const total=Math.max(1,bull+bear+neu);return{bullish:Math.round(bull/total*100),neutral:Math.round(neu/total*100),bearish:Math.round(bear/total*100)}}
function fundamental(name){if(/NVIDIA|Microsoft|Alphabet|Apple|Amazon|Meta|JPMorgan|삼성전자|SK하이닉스|TSMC/i.test(name))return 78;if(/Tesla|Palantir|Oracle|한미반도체|두산|NAVER/i.test(name))return 68;return 62}
function calc(q,s,m){const news=Math.max(0,Math.min(100,50+(s.bullish-s.bearish)*.5)),price=Math.max(0,Math.min(100,50+q.change*8)),vol=q.avgVolume?Math.max(0,Math.min(100,50+((q.volume/q.avgVolume)-1)*35)):50,sector=Math.max(0,Math.min(100,50+m*10)),exp=Math.max(20,Math.min(90,Math.round(50+s.bullish*.45-s.bearish*.35))),fund=fundamental(''),risk=q.change<-5?35:q.change>8?45:70;return Math.round(news*.25+price*.2+vol*.15+sector*.15+exp*.1+fund*.1+risk*.05)}
async function one(s,m,all){let q={price:null,change:0,history:[],volume:0,avgVolume:0};try{q=await yahoo(s[1])}catch{}let rel=all.filter(n=>new RegExp(escRe(s[0]),'i').test(n.title));const se=sentiment(rel.length?rel:all),score=calc(q,se,m),reason=se.bullish>se.bearish?'뉴스 심리 우호 + ':'뉴스 혼조 + '+(q.change>=0?'가격 모멘텀 양호':'가격 모멘텀 약세');return{name:s[0],ticker:s[1],market:s[2],score,signal:score>=85?'강한 관심':score>=75?'관심':score>=65?'관찰':'주의',reason}}
async function markets(){const o={};await Promise.all(Object.entries(ASSETS).map(async([n,t])=>{try{const q=await yahoo(t,'5d');o[n]={price:q.price,change:q.change}}catch{o[n]={price:null,change:0}}}));return o}
export default async function handler(req,res){try{const mk=await markets(),m=mk['S&P 500']?.change||0,base=await newsFor('주식 증시 AI 반도체 금리 환율 미국주식 한국주식');const out=(await Promise.all(U.map(async s=>{try{return await one(s,m,base)}catch{return null}}))).filter(Boolean);out.sort((a,b)=>b.score-a.score);const news=base.filter(n=>Date.now()-new Date(n.pubDate).getTime()<48*3600*1000).slice(0,12);res.status(200).json({updatedAt:new Date().toISOString(),markets:mk,picks:out.slice(0,8),news})}catch(e){res.status(500).json({error:String(e),updatedAt:new Date().toISOString(),markets:{},picks:[],news:[]})}}
